apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrum-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrum-app
      version: blue
  template:
    metadata:
      labels:
        app: scrum-app
        version: blue
    spec:
      containers:
        - name: scrum-app
          image: user-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/userdb"
          ports:
            - containerPort: 5000
